swagger: "2.0"
info:
  title: Test iam
  description: Title
  version: 1.0.0
schemes:
  - http
securityDefinitions:
  OauthSecurity:
    type: oauth2
    flow: accessCode
    authorizationUrl: 'http://localhost:8080/realms/test/protocol/openid-connect/auth'
    tokenUrl: 'http://localhost:8080/realms/test/protocol/openid-connect/token'
basePath: '/api/v1'
host: localhost:8082
security:
  - OauthSecurity: [ ]
tags:
  - name: System
    description: System endpoints
  - name: User
    description: User endpoints
  - name: Auth
    description: Auth endpoints
paths:
  /health:
    get:
      summary: Healthcheck endpoint
      tags:
        - System
      operationId: GetHealth
      responses:
        200:
          description: Success
        default:
          description: Unexpected error.
          schema:
            $ref: "#/definitions/Error"
  /login:
    get:
      tags:
        - Auth
      summary: login through oauth2 server
      security: [ ]
      responses:
        '200':
          description: login
          schema:
            properties:
              access_token:
                type: string
                format: string
        default:
          description: error
          schema:
            $ref: "#/definitions/Error"
  /callback:
    get:
      tags:
        - Auth
      summary: return access_token
      security: [ ]
      responses:
        '200':
          description: login
          schema:
            properties:
              access_token:
                type: string
                format: string
        default:
          description: error
          schema:
            $ref: "#/definitions/Error"

  /user/me/roles:
    get:
      description: Get user roles
      tags:
        - User
      operationId: GetUserRoles
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              type: string
        default:
          description: Unexpected error.
          schema:
            $ref: "#/definitions/Error"
definitions:
  LoginInfo:
    type: object
    properties:
      username:
        type: string
        description: Username
        example: test
      password:
        type: string
        description: Password
        example: 1234
  TokenPair:
    type: object
    properties:
      AccessToken:
        $ref: "#/definitions/AccessToken"
      RefreshToken:
        $ref: "#/definitions/RefreshToken"
  AccessToken:
    type: string
  RefreshToken:
    type: string

  principal:
    type: string

  Error:
    type: object
    properties:
      message:
        type: string
        description: Error message
      code:
        type: integer
        format: int32
        description: Error code
